Q2a:
	gcc Q2A_P1.c -o q2a1
	gcc Q2A_P2.c -o q2a2
	./q2a1 &
	sleep 5
	./q2a2

Q2b:
	gcc Q2B_P1.c -o q2b1
	gcc Q2B_P2.c -o q2b2
	./q2b2 &
	sleep 5
	./q2b1

Q2c:
	gcc Q2C_P1.c -o q2c1
	gcc Q2C_P2.c -o q2c2
	./q2c1 &
	sleep 5
	./q2c2